#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &

internal_monitor=eDP-1
external_monitor=DP-3

if xrandr | grep "$external_monitor connected"; then
    xrandr --output $internal_monitor --off --output $external_monitor --auto --primary
    bspc monitor $external_monitor -d 1 2 3 4 5 6 7 8 9 0
    bspc monitor $internal_monitor --remove
else
    xrandr --output $internal_monitor --auto --primary
    bspc monitor $external_monitor --remove
    bspc monitor $internal_monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# stuff that needs to load after monitors have been configured
~/.fehbg &

# whatever happens, focus the first desktop and adopt orphans
bspc desktop -f ^1
bspc wm --adopt-orphans

bspc config border_width         1
bspc config window_gap           12
bspc config top_padding          27
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# make alt pointer_modifier so we can resize and move with alt
bspc config pointer_modifier mod1
# ignore EWMH suggestions for paddings (polybar resets top_padding)
bspc config ignore_ewmh_struts true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a firefox desktop=^3

# ~/.config/polybar/launch.sh
